sudo: required
services:
  - docker
language: node_js
node_js:
  - "node"
install:
  - echo "moving on to the script in Dockerfile"
script:
  - scripts/docker-setup-travis.sh
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
