sudo: required
services:
  - docker
language: node_js
node_js:
  - "node"
before_install:
  - echo "ENV TRAVIS ${TRAVIS}" >> Dockerfile
install:
  - docker build -t vikinggarage/viking-garage-frontend:latest ./
script:
  - docker run -p 127.0.0.1:80:3000 --name viking-garage-frontend vikinggarage/viking-garage-frontend:latest
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
