sudo: required
services:
  - docker
language: node_js
node_js:
  - "node"
install:
  - docker build -t vikinggarage/viking-garage-frontend:latest ./
script:
  - docker run -p 127.0.0.1:80:3000 --name viking-garage-frontend vikinggarage/viking-garage-frontend:latest npm test
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker tag viking-garage-frontend vikinggarage/viking-garage-frontend;
      docker push vikinggarage/viking-garage-frontend;
    else
      docker tag viking-garage-frontend vikinggarage/viking-garage-frontend-dev;
      docker push vikinggarage/viking-garage-frontend-dev;
    fi
